const CANVAS = { WIDTH: 790, HEIGHT: 580 };
const INITIAL_LOCATION = { x: CANVAS.WIDTH / 2, y: CANVAS.HEIGHT / 2 };
const SPEED = { x: 5, y: 5 };
const DIAMETER = 60;
const BALL_COLOR = 100;
const BACKGROUND_COLOR = 255;
const BORDER_COLOR = 0;
const BORDER_THIKNESS = 3;
